# Default recipe
default:
    @just --list

prepare_shaders glsl_version glsl_version_str:
    rm -rf "src/shaders/versions/{{glsl_version}}"
    mkdir -p "src/shaders/versions/{{glsl_version}}"
    for file in $(find src/shaders -type f ! -path 'src/shaders/versions/*'); do \
        dest="src/shaders/versions/{{glsl_version}}/`basename $file`"; \
        mkdir -p "`dirname $dest`"; \
        sed "s/^#version.*/#version {{glsl_version_str}}/" "$file" > "$dest"; \
    done

# Build one or all WASM simulations
#   just wasm                  <- builds all binaries in the workspace
#   just wasm electro_magnetic <- builds only that binary
wasm sim="":
    #!/usr/bin/env bash
    set -e
    
    mkdir -p ../app/static/wasm

    export GLSL_VERSION=v300es
    just prepare_shaders v300es "300 es"

    if [ -z "{{sim}}" ]; then
        echo "Building all binaries..."
        cargo build --release --target wasm32-unknown-unknown
        
        find target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm" -exec cp {} ../app/static/wasm/ \;
        echo "Successfully copied all WASM files to ../app/static/wasm/"
    else
        echo "Building simulation: {{sim}}..."
        cargo build --release --target wasm32-unknown-unknown --bin {{sim}}
        cp target/wasm32-unknown-unknown/release/{{sim}}.wasm ../app/static/wasm/
        echo "Successfully copied {{sim}}.wasm to ../app/static/wasm/"
    fi
    #
# Build and run a simulation locally
run_sim sim="":
    export GLSL_VERSION=v330
    just prepare_shaders v330 "330"
    cargo build --release --bin {{sim}}
    ./target/release/{{sim}}

build_sim sim="":
    export GLSL_VERSION=v330
    just prepare_shaders v330 "330"
    cargo build --bin {{sim}}

# Clean build artifacts
clean:
    cargo clean
    rm -rf ../app/static/wasm/*.wasm
